# Generated by Django 3.0.5 on 2020-04-13 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hastag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagged_tweets', models.ManyToManyField(related_name='tags', to='messaging.Tweet', verbose_name='hashtags')),
            ],
        ),
    ]
