# Generated by Django 3.0.5 on 2020-04-13 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_hastag'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hastag',
            new_name='Hashtag',
        ),
    ]
